//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialLogisticsSystem.AppPortal.Cm {
    
    
    public partial class Config {
        
        /// <summary>
        /// cbk_input control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxCallback.ASPxCallback cbk_input;
        
        /// <summary>
        /// popConfig control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxPopupControl.ASPxPopupControl popConfig;
        
        /// <summary>
        /// viewMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.MainToolBar viewMenu;
        
        /// <summary>
        /// cbbTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.ThemeSelector cbbTheme;
        
        /// <summary>
        /// search_type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.ComboxSystem search_type;
        
        /// <summary>
        /// start_city control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.CityLookUp start_city;
        
        /// <summary>
        /// end_city control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.CityLookUp end_city;
        
        /// <summary>
        /// get_free control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxCheckBox get_free;
        
        /// <summary>
        /// ASPxCheckBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxCheckBox other_free;
        
        /// <summary>
        /// set_free control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxCheckBox set_free;
        
        /// <summary>
        /// txt_account_name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxTextBox txt_account_name;
        
        /// <summary>
        /// txt_account_password control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_account_password;
        
        /// <summary>
        /// txt_sms_singer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxTextBox txt_sms_singer;
    }
}
