//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialLogisticsSystem.AppPortal.Business {
    
    
    public partial class Stowage {
        
        /// <summary>
        /// txt_stowage_number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxTextBox txt_stowage_number;
        
        /// <summary>
        /// date_range control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.DateRange date_range;
        
        /// <summary>
        /// gridStowage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxGridView gridStowage;
        
        /// <summary>
        /// stowageDetailDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource stowageDetailDataSource;
        
        /// <summary>
        /// stowageDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource stowageDataSource;
        
        /// <summary>
        /// productionDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource productionDataSource;
        
        /// <summary>
        /// stowageStatueDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource stowageStatueDataSource;
        
        /// <summary>
        /// productionList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.ProductionList productionList;
        
        /// <summary>
        /// pop_PrintConstruct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxPopupControl.ASPxPopupControl pop_PrintConstruct;
    }
}
