//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialLogisticsSystem.AppPortal.Business {
    
    
    public partial class Transfer {
        
        /// <summary>
        /// txt_way_number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxTextBox txt_way_number;
        
        /// <summary>
        /// date_range control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.DateRange date_range;
        
        /// <summary>
        /// gridTransfer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.UserControl.ASPxGridView gridTransfer;
        
        /// <summary>
        /// transferDetailDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource transferDetailDataSource;
        
        /// <summary>
        /// transferDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource transferDataSource;
        
        /// <summary>
        /// transferStatueDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource transferStatueDataSource;
        
        /// <summary>
        /// productionList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpecialLogisticsSystem.AppPortal.UserControls.ProductionList productionList;
        
        /// <summary>
        /// pop_PrintConstruct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxPopupControl.ASPxPopupControl pop_PrintConstruct;
    }
}
